/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppPortalIndexRouteImport } from './routes/_app/portal.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AppTemplatesNewRouteImport } from './routes/_app/templates.new'
import { Route as AppTemplatesIdRouteImport } from './routes/_app/templates/$id'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppPortalTasksRouteImport } from './routes/_app/portal.tasks'
import { Route as AppPortalReportsRouteImport } from './routes/_app/portal.reports'
import { Route as AppPortalPhotosRouteImport } from './routes/_app/portal.photos'
import { Route as AppPortalChatRouteImport } from './routes/_app/portal.chat'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents.new'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminUsageRouteImport } from './routes/_admin/admin.usage'
import { Route as AdminAdminSubscriptionsRouteImport } from './routes/_admin/admin.subscriptions'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin/admin.projects'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin/admin.payments'
import { Route as AdminAdminPackagesRouteImport } from './routes/_admin/admin.packages'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin.audit-logs'
import { Route as AdminAdminAdvertisementsRouteImport } from './routes/_admin/admin.advertisements'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId.index'
import { Route as AdminAdminCompaniesIndexRouteImport } from './routes/_admin/admin.companies.index'
import { Route as AppTemplatesIdUseRouteImport } from './routes/_app/templates/$id.use'
import { Route as AppProjectsProjectIdTeamRouteImport } from './routes/_app/projects/$projectId.team'
import { Route as AppProjectsProjectIdTasksRouteImport } from './routes/_app/projects/$projectId.tasks'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId.settings'
import { Route as AppProjectsProjectIdReportsRouteImport } from './routes/_app/projects/$projectId.reports'
import { Route as AppProjectsProjectIdPhotosRouteImport } from './routes/_app/projects/$projectId.photos'
import { Route as AppProjectsProjectIdGanttRouteImport } from './routes/_app/projects/$projectId.gantt'
import { Route as AppProjectsProjectIdDocumentsRouteImport } from './routes/_app/projects/$projectId.documents'
import { Route as AppProjectsProjectIdChecklistsRouteImport } from './routes/_app/projects/$projectId.checklists'
import { Route as AppProjectsProjectIdChatRouteImport } from './routes/_app/projects/$projectId.chat'
import { Route as AppProjectsProjectIdCalendarRouteImport } from './routes/_app/projects/$projectId.calendar'
import { Route as AdminAdminCompaniesCompanyIdRouteImport } from './routes/_admin/admin.companies.$companyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalIndexRoute = AppPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPortalRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalTasksRoute = AppPortalTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalReportsRoute = AppPortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalPhotosRoute = AppPortalPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalChatRoute = AppPortalChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsageRoute = AdminAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSubscriptionsRoute = AdminAdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPackagesRoute = AdminAdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdvertisementsRoute =
  AdminAdminAdvertisementsRouteImport.update({
    id: '/admin/advertisements',
    path: '/admin/advertisements',
    getParentRoute: () => AdminRoute,
  } as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AdminAdminCompaniesIndexRoute =
  AdminAdminCompaniesIndexRouteImport.update({
    id: '/admin/companies/',
    path: '/admin/companies/',
    getParentRoute: () => AdminRoute,
  } as any)
const AppTemplatesIdUseRoute = AppTemplatesIdUseRouteImport.update({
  id: '/use',
  path: '/use',
  getParentRoute: () => AppTemplatesIdRoute,
} as any)
const AppProjectsProjectIdTeamRoute =
  AppProjectsProjectIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdTasksRoute =
  AppProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdReportsRoute =
  AppProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPhotosRoute =
  AppProjectsProjectIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdGanttRoute =
  AppProjectsProjectIdGanttRouteImport.update({
    id: '/gantt',
    path: '/gantt',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDocumentsRoute =
  AppProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdChecklistsRoute =
  AppProjectsProjectIdChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdChatRoute =
  AppProjectsProjectIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdCalendarRoute =
  AppProjectsProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AdminAdminCompaniesCompanyIdRoute =
  AdminAdminCompaniesCompanyIdRouteImport.update({
    id: '/admin/companies/$companyId',
    path: '/admin/companies/$companyId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/portal': typeof AppPortalRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/admin/advertisements': typeof AdminAdminAdvertisementsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/packages': typeof AdminAdminPackagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/usage': typeof AdminAdminUsageRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/portal/chat': typeof AppPortalChatRoute
  '/portal/photos': typeof AppPortalPhotosRoute
  '/portal/reports': typeof AppPortalReportsRoute
  '/portal/tasks': typeof AppPortalTasksRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/templates/$id': typeof AppTemplatesIdRouteWithChildren
  '/templates/new': typeof AppTemplatesNewRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/portal/': typeof AppPortalIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/admin/companies/$companyId': typeof AdminAdminCompaniesCompanyIdRoute
  '/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/projects/$projectId/chat': typeof AppProjectsProjectIdChatRoute
  '/projects/$projectId/checklists': typeof AppProjectsProjectIdChecklistsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/gantt': typeof AppProjectsProjectIdGanttRoute
  '/projects/$projectId/photos': typeof AppProjectsProjectIdPhotosRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/team': typeof AppProjectsProjectIdTeamRoute
  '/templates/$id/use': typeof AppTemplatesIdUseRoute
  '/admin/companies/': typeof AdminAdminCompaniesIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/admin/advertisements': typeof AdminAdminAdvertisementsRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/packages': typeof AdminAdminPackagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/usage': typeof AdminAdminUsageRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/portal/chat': typeof AppPortalChatRoute
  '/portal/photos': typeof AppPortalPhotosRoute
  '/portal/reports': typeof AppPortalReportsRoute
  '/portal/tasks': typeof AppPortalTasksRoute
  '/templates/$id': typeof AppTemplatesIdRouteWithChildren
  '/templates/new': typeof AppTemplatesNewRoute
  '/admin': typeof AdminAdminIndexRoute
  '/portal': typeof AppPortalIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/admin/companies/$companyId': typeof AdminAdminCompaniesCompanyIdRoute
  '/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/projects/$projectId/chat': typeof AppProjectsProjectIdChatRoute
  '/projects/$projectId/checklists': typeof AppProjectsProjectIdChecklistsRoute
  '/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/projects/$projectId/gantt': typeof AppProjectsProjectIdGanttRoute
  '/projects/$projectId/photos': typeof AppProjectsProjectIdPhotosRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/projects/$projectId/team': typeof AppProjectsProjectIdTeamRoute
  '/templates/$id/use': typeof AppTemplatesIdUseRoute
  '/admin/companies': typeof AdminAdminCompaniesIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/portal': typeof AppPortalRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_admin/admin/advertisements': typeof AdminAdminAdvertisementsRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/packages': typeof AdminAdminPackagesRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/_admin/admin/usage': typeof AdminAdminUsageRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/portal/chat': typeof AppPortalChatRoute
  '/_app/portal/photos': typeof AppPortalPhotosRoute
  '/_app/portal/reports': typeof AppPortalReportsRoute
  '/_app/portal/tasks': typeof AppPortalTasksRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/templates/$id': typeof AppTemplatesIdRouteWithChildren
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/portal/': typeof AppPortalIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_admin/admin/companies/$companyId': typeof AdminAdminCompaniesCompanyIdRoute
  '/_app/projects/$projectId/calendar': typeof AppProjectsProjectIdCalendarRoute
  '/_app/projects/$projectId/chat': typeof AppProjectsProjectIdChatRoute
  '/_app/projects/$projectId/checklists': typeof AppProjectsProjectIdChecklistsRoute
  '/_app/projects/$projectId/documents': typeof AppProjectsProjectIdDocumentsRoute
  '/_app/projects/$projectId/gantt': typeof AppProjectsProjectIdGanttRoute
  '/_app/projects/$projectId/photos': typeof AppProjectsProjectIdPhotosRoute
  '/_app/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/tasks': typeof AppProjectsProjectIdTasksRoute
  '/_app/projects/$projectId/team': typeof AppProjectsProjectIdTeamRoute
  '/_app/templates/$id/use': typeof AppTemplatesIdUseRoute
  '/_admin/admin/companies/': typeof AdminAdminCompaniesIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/approvals'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/portal'
    | '/settings'
    | '/users'
    | '/admin/advertisements'
    | '/admin/audit-logs'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/admin/users'
    | '/documents/new'
    | '/portal/chat'
    | '/portal/photos'
    | '/portal/reports'
    | '/portal/tasks'
    | '/projects/$projectId'
    | '/templates/$id'
    | '/templates/new'
    | '/admin/'
    | '/portal/'
    | '/projects/'
    | '/templates/'
    | '/admin/companies/$companyId'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/checklists'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/templates/$id/use'
    | '/admin/companies/'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/approvals'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/admin/advertisements'
    | '/admin/audit-logs'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/usage'
    | '/admin/users'
    | '/documents/new'
    | '/portal/chat'
    | '/portal/photos'
    | '/portal/reports'
    | '/portal/tasks'
    | '/templates/$id'
    | '/templates/new'
    | '/admin'
    | '/portal'
    | '/projects'
    | '/templates'
    | '/admin/companies/$companyId'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/checklists'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/templates/$id/use'
    | '/admin/companies'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/approvals'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/notifications'
    | '/_app/portal'
    | '/_app/settings'
    | '/_app/users'
    | '/_admin/admin/advertisements'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/packages'
    | '/_admin/admin/payments'
    | '/_admin/admin/projects'
    | '/_admin/admin/settings'
    | '/_admin/admin/subscriptions'
    | '/_admin/admin/usage'
    | '/_admin/admin/users'
    | '/_app/documents/new'
    | '/_app/portal/chat'
    | '/_app/portal/photos'
    | '/_app/portal/reports'
    | '/_app/portal/tasks'
    | '/_app/projects/$projectId'
    | '/_app/templates/$id'
    | '/_app/templates/new'
    | '/_admin/admin/'
    | '/_app/portal/'
    | '/_app/projects/'
    | '/_app/templates/'
    | '/_admin/admin/companies/$companyId'
    | '/_app/projects/$projectId/calendar'
    | '/_app/projects/$projectId/chat'
    | '/_app/projects/$projectId/checklists'
    | '/_app/projects/$projectId/documents'
    | '/_app/projects/$projectId/gantt'
    | '/_app/projects/$projectId/photos'
    | '/_app/projects/$projectId/reports'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/tasks'
    | '/_app/projects/$projectId/team'
    | '/_app/templates/$id/use'
    | '/_admin/admin/companies/'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/': {
      id: '/_app/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AppPortalIndexRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/tasks': {
      id: '/_app/portal/tasks'
      path: '/tasks'
      fullPath: '/portal/tasks'
      preLoaderRoute: typeof AppPortalTasksRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/reports': {
      id: '/_app/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AppPortalReportsRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/photos': {
      id: '/_app/portal/photos'
      path: '/photos'
      fullPath: '/portal/photos'
      preLoaderRoute: typeof AppPortalPhotosRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/chat': {
      id: '/_app/portal/chat'
      path: '/chat'
      fullPath: '/portal/chat'
      preLoaderRoute: typeof AppPortalChatRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/usage': {
      id: '/_admin/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminAdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/subscriptions': {
      id: '/_admin/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/packages': {
      id: '/_admin/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminAdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/advertisements': {
      id: '/_admin/admin/advertisements'
      path: '/admin/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_admin/admin/companies/': {
      id: '/_admin/admin/companies/'
      path: '/admin/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminAdminCompaniesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/templates/$id/use': {
      id: '/_app/templates/$id/use'
      path: '/use'
      fullPath: '/templates/$id/use'
      preLoaderRoute: typeof AppTemplatesIdUseRouteImport
      parentRoute: typeof AppTemplatesIdRoute
    }
    '/_app/projects/$projectId/team': {
      id: '/_app/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof AppProjectsProjectIdTeamRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/tasks': {
      id: '/_app/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/reports': {
      id: '/_app/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof AppProjectsProjectIdReportsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/photos': {
      id: '/_app/projects/$projectId/photos'
      path: '/photos'
      fullPath: '/projects/$projectId/photos'
      preLoaderRoute: typeof AppProjectsProjectIdPhotosRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/gantt': {
      id: '/_app/projects/$projectId/gantt'
      path: '/gantt'
      fullPath: '/projects/$projectId/gantt'
      preLoaderRoute: typeof AppProjectsProjectIdGanttRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/documents': {
      id: '/_app/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AppProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/checklists': {
      id: '/_app/projects/$projectId/checklists'
      path: '/checklists'
      fullPath: '/projects/$projectId/checklists'
      preLoaderRoute: typeof AppProjectsProjectIdChecklistsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/chat': {
      id: '/_app/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof AppProjectsProjectIdChatRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/calendar': {
      id: '/_app/projects/$projectId/calendar'
      path: '/calendar'
      fullPath: '/projects/$projectId/calendar'
      preLoaderRoute: typeof AppProjectsProjectIdCalendarRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_admin/admin/companies/$companyId': {
      id: '/_admin/admin/companies/$companyId'
      path: '/admin/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAdvertisementsRoute: typeof AdminAdminAdvertisementsRoute
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminPackagesRoute: typeof AdminAdminPackagesRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSubscriptionsRoute: typeof AdminAdminSubscriptionsRoute
  AdminAdminUsageRoute: typeof AdminAdminUsageRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCompaniesCompanyIdRoute: typeof AdminAdminCompaniesCompanyIdRoute
  AdminAdminCompaniesIndexRoute: typeof AdminAdminCompaniesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAdvertisementsRoute: AdminAdminAdvertisementsRoute,
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminPackagesRoute: AdminAdminPackagesRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSubscriptionsRoute: AdminAdminSubscriptionsRoute,
  AdminAdminUsageRoute: AdminAdminUsageRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCompaniesCompanyIdRoute: AdminAdminCompaniesCompanyIdRoute,
  AdminAdminCompaniesIndexRoute: AdminAdminCompaniesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppDocumentsRouteChildren {
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsNewRoute: AppDocumentsNewRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppPortalRouteChildren {
  AppPortalChatRoute: typeof AppPortalChatRoute
  AppPortalPhotosRoute: typeof AppPortalPhotosRoute
  AppPortalReportsRoute: typeof AppPortalReportsRoute
  AppPortalTasksRoute: typeof AppPortalTasksRoute
  AppPortalIndexRoute: typeof AppPortalIndexRoute
}

const AppPortalRouteChildren: AppPortalRouteChildren = {
  AppPortalChatRoute: AppPortalChatRoute,
  AppPortalPhotosRoute: AppPortalPhotosRoute,
  AppPortalReportsRoute: AppPortalReportsRoute,
  AppPortalTasksRoute: AppPortalTasksRoute,
  AppPortalIndexRoute: AppPortalIndexRoute,
}

const AppPortalRouteWithChildren = AppPortalRoute._addFileChildren(
  AppPortalRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdCalendarRoute: typeof AppProjectsProjectIdCalendarRoute
  AppProjectsProjectIdChatRoute: typeof AppProjectsProjectIdChatRoute
  AppProjectsProjectIdChecklistsRoute: typeof AppProjectsProjectIdChecklistsRoute
  AppProjectsProjectIdDocumentsRoute: typeof AppProjectsProjectIdDocumentsRoute
  AppProjectsProjectIdGanttRoute: typeof AppProjectsProjectIdGanttRoute
  AppProjectsProjectIdPhotosRoute: typeof AppProjectsProjectIdPhotosRoute
  AppProjectsProjectIdReportsRoute: typeof AppProjectsProjectIdReportsRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdTasksRoute: typeof AppProjectsProjectIdTasksRoute
  AppProjectsProjectIdTeamRoute: typeof AppProjectsProjectIdTeamRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdCalendarRoute: AppProjectsProjectIdCalendarRoute,
  AppProjectsProjectIdChatRoute: AppProjectsProjectIdChatRoute,
  AppProjectsProjectIdChecklistsRoute: AppProjectsProjectIdChecklistsRoute,
  AppProjectsProjectIdDocumentsRoute: AppProjectsProjectIdDocumentsRoute,
  AppProjectsProjectIdGanttRoute: AppProjectsProjectIdGanttRoute,
  AppProjectsProjectIdPhotosRoute: AppProjectsProjectIdPhotosRoute,
  AppProjectsProjectIdReportsRoute: AppProjectsProjectIdReportsRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdTasksRoute: AppProjectsProjectIdTasksRoute,
  AppProjectsProjectIdTeamRoute: AppProjectsProjectIdTeamRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppTemplatesIdRouteChildren {
  AppTemplatesIdUseRoute: typeof AppTemplatesIdUseRoute
}

const AppTemplatesIdRouteChildren: AppTemplatesIdRouteChildren = {
  AppTemplatesIdUseRoute: AppTemplatesIdUseRoute,
}

const AppTemplatesIdRouteWithChildren = AppTemplatesIdRoute._addFileChildren(
  AppTemplatesIdRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPortalRoute: typeof AppPortalRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppTemplatesIdRoute: typeof AppTemplatesIdRouteWithChildren
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPortalRoute: AppPortalRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppTemplatesIdRoute: AppTemplatesIdRouteWithChildren,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
