// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { supabaseAdmin } from './client.server'
import { verifySignedAppSessionToken } from '@/lib/app-session-token'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const token = request.headers.get('x-app-session');

    if (!token) {
      throw new Error('Unauthorized: No app session provided');
    }

    const signedSession = verifySignedAppSessionToken(token);
    if (signedSession) {
      return next({
        context: {
          supabase: supabaseAdmin,
          userId: signedSession.userId,
          token,
        },
      });
    }

    const { data: session, error } = await supabaseAdmin
      .from('app_sessions')
      .select('user_id, expires_at')
      .eq('token', token)
      .maybeSingle();
    if (error || !session) {
      throw new Error('Unauthorized: Invalid app session');
    }
    if (new Date(session.expires_at).getTime() <= Date.now()) {
      throw new Error('Unauthorized: Session expired');
    }

    return next({
      context: {
        supabase: supabaseAdmin,
        userId: session.user_id,
        token,
      },
    });
  },
);
