// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getAppSessionToken } from '@/lib/app-auth-client'

export const attachAppAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = getAppSessionToken()
    return next({
      headers: token ? { 'x-app-session': token } : {},
    })
  },
)
